app/routes/users.py
from datetime import datetime
from zoneinfo import ZoneInfo

from flask import Blueprint, jsonify, request
from flask_login import current_user, login_required, login_user, logout_user

from app.extensions import bcrypt
from app.repositories.UserRepository import UserRepository as user_repository

users = Blueprint("users", __name__)


@users.route("/admin/users")
@login_required
def index():
    if not current_user and current_user.is_admin:
        return jsonify({"error": "Access denied"}), 403

    all_users = user_repository.get_all()
    return jsonify({"users": [user.to_json() for user in all_users], "success": "User"})


@users.route("/register", methods=["POST"])
def register():
    try:
        data = request.json
        if not data:
            return jsonify({"error": "No JSON received"}), 400

        username = data.get("username")
        password = data.get("password")
        email = data.get("email")
        is_active = data.get("is_active", False)
        role = data.get("role", ["ROLE_USER"])

        if not email or not password or not username:
            return jsonify({"error": "Email, Username, and Password are required"}), 400

        existing_user = user_repository.get_by_email(email)
        if existing_user:
            return jsonify({"error": "Email already registered"}), 409

        password_hash = bcrypt.generate_password_hash(password).decode("utf-8")
        user_data = {
            "email": email,
            "username": username,
            "password": password_hash,
            "is_active": is_active,
            "role": role,
        }
        user_repository.create(user_data)

        return jsonify({"success": "User registered"}), 201

    except Exception as e:
        return jsonify({"error": str(e)}), 500


@users.route("/login", methods=["POST"])
def login():
    try:
        data = request.json
        if not data:
            return jsonify({"error": "No JSON received"}), 400

        email = data.get("email")
        password = data.get("password")

        if not email or not password:
            return jsonify({"error": "Email and password are required"}), 400

        user = user_repository.get_by_email(email)
        if user and bcrypt.check_password_hash(user.password, password):
            if user.is_active:
                now = datetime.now(ZoneInfo("Europe/Paris"))
                user_repository.update(user.id, last_active=now)
                login_user(user)
                return jsonify({"success": "Login successful"}), 200
            return jsonify({"error": "User not activated"}), 403

        return jsonify({"error": "Wrong Email or Password"}), 404

    except Exception as e:
        return jsonify({"error": str(e)}), 500


@users.route("/logout", methods=["POST"])
def logout():
    logout_user()
    return jsonify({"success": "Logout successful"}), 200


@users.route("/user/<int:user_id>/delete", methods=["DELETE"])
def delete_user(user_id):
    try:
        user = user_repository.get_by_id(user_id)
        if not user:
            return jsonify({"error": "User not found"}), 404

        user_repository.delete(user_id)

        return jsonify({"success": "User deleted"}), 200

    except Exception as e:
        return jsonify({"error": str(e)}), 500

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Titre par défaut {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="/css/style.css">
</head>
<body>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        {% endif %}
    {% endwith %}


  {% block body %} Body par défaut {% endblock %}
</body>
</html>

app/templates/download.html
{% extends "base.html" %}
{% block title %} DOWNLOAD {% endblock %}
{% block body %}
<a href="{{ url_for('download', filename=filename) }}">download file</a>
{% endblock %}

app/templates/filters.html
{% extends "base.html" %}
{% block title %} FILTERS {% endblock %}
{% block body %}
  <h1>Filters</h1>
  <p>{{ text }}</p>
  <p>{{ text|upper}}</p>
  <p>{{ text|lower }}</p>
  <p>{{ text|replace('n', 'TN') }}</p>
  <p>{{ text|title }}</p>
  <p>{{ text|reverse_string }}</p>
  <p>{{ text|repeat }}</p>
  <p>{{ text|repeat(2) }}</p>
  <p>{{ text|alternate_case }}</p>
  <p>{{ text|alternate_case|repeat(10) }}</p>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block title %} TEST {% endblock %}

{% block body %}

{% if current_user.is_authenticated %}
  <h1>Hello, {{ current_user.username }} !</h1>
  <ul>
    <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
  </ul>
{% endif %}

<!-- Formulaire d'inscription -->
<form action="{{ url_for('users.register') }}" method="POST">
  <h3>Register</h3>
  <input type="text" name="username" placeholder="Username" required>
  <input type="password" name="password" placeholder="Password" required>
  <input type="email" name="email" placeholder="Email" required>
  <button type="submit">Register</button>
</form>

<!-- Formulaire de connexion -->
<form action="{{ url_for('users.login') }}" method="POST">
  <h3>Login</h3>
  <input type="email" name="email" placeholder="Email" required>
  <input type="password" name="password" placeholder="Password" required>
  <button type="submit">Login</button>
</form>

<!-- Liste des utilisateurs -->
<h3>Users List</h3>
<table border="1">
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Active</th>
    <th>Role</th>
    <th>Created At</th>
    <th>Last Active</th>
    <th>Actions</th>
  </tr>
  {% for user in users %}
  <tr>
    <td>{{ user.username }}</td>
    <td>{{ user.email }}</td>
    <td>{{ user.is_active }}</td>
    <td>{{ user.role }}</td>
    <td>{{ user.created_at }}</td>
    <td>{{ user.last_active }}</td>
    <td>
      <a href="{{ url_for('users.delete_user', user_id=user.id) }}">Delete</a>
    </td>
  </tr>
  {% endfor %}
</table>

{% endblock %}

app/templates/indexe.html
{% extends "base.html" %}
{% block title %} TEST {% endblock %}

{% block body %}
<p>ceci est le body de index.html</p>

<h1>Hello {{ name }}</h1>
    <p>{{ mylist }}</p>
    <ul>
        {% for i in mylist %}
            <li {% if i == 5 %} style="color:red" {% endif %}> {{ i }} </li>
        {% endfor %}
    </ul>

    <p>{{ ines }}</p>

    <a href="{{ url_for('filters') }}">COUCOU</a>


<h1>form</h1>

    <form method="POST" action="{{ url_for('index') }}">
        <input type="text" name="username" placeholder="name">
        <input type="password" name="password" placeholder="password">
        <button>valider</button>
    </form>

<h1>file</h1>

    <form method="POST" action="{{ url_for('file') }}" enctype="multipart/form-data">
        <input type="file" name="file" placeholder="file" accept="image/jpeg, text/plain, image/png, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">
        <button>valider</button>
    </form>

<h1>convert file</h1>

    <form method="POST" action="{{ url_for('convert_file_two') }}" enctype="multipart/form-data">
        <input type="file" name="file" placeholder="file" accept="image/jpeg, text/plain, image/png, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">
        <button>valider</button>
    </form>

<h1>Javascript Json Request</h1>

<button id="post_btn">Send JSON Request</button>

<h1>static file</h1>
<img src="/img/img.jpg">

<h1>SESSION</h1>
<p>{{ message }}</p>

<a href=" {{ url_for('set_data') }}">Set Session</a>
<a href=" {{ url_for('get_data') }}">Get Session Data</a>
<a href=" {{ url_for('erase_data') }}">Erase Session Data</a>


<h1>COOKIES</h1>
<p>{{ message }}</p>
<a href=" {{ url_for('set_cookie') }}">Set Cookie</a>
<a href=" {{ url_for('get_cookie') }}">Get Cookie</a>
<a href=" {{ url_for('erase_cookie') }}">Erase Cookie</a>


<h1>flashes</h1>

    <form method="POST" action="{{ url_for('login') }}">
        <input type="text" name="username" placeholder="name">
        <input type="password" name="password" placeholder="password">
        <button>valider</button>
    </form>

<script>
    const postBtn = document.getElementById('post_btn');
    const jsonData = {name: 'Ines', greeting: 'Hello'};

    postBtn.addEventListener('click', () => {
        fetch('{{ url_for("handle_post") }}', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json; charset=utf-8'
            },
            body: JSON.stringify(jsonData)
        })
        .then(response => {
            if (!response.ok) {
                throw new Error(`Erreur: ${response.status}`);
            }
            return response.json();
        })
        .then(data => {
            console.log('Succès:', data);
        })
        .catch(error => {
            console.error('Erreur lors de l\'envoi:', error);
        });
    });
</script>
{% endblock %}